vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'\
    mappings:
        user_image:
            namer: vich_uploader.namer_origname
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
